# Generated by Django 4.0.2 on 2022-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', models.CharField(max_length=100)),
                ('category_desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
